id: P1A3440A1
initial_creation_type: input
source_metadata:
  title: Khenpo Yönten Gyatso Series
  language: pt
  description: 'Texts by the learned Khenpo Yönten Gyatso (yon tan rgya mtsho, 19th–20th
    C.) of Gemang (dge mang):'
  volume:
    525409988dfb47308a906674b1bbf4b2:
      title: 'The Prayer of the Ground, Path & Fruition from the Heart-Essence of
        the Vast Expanse:'
      parent: Dzogchen
created_at: '2022-03-01T00:30:35.340363'
last_modified_at: '2022-03-01T00:30:35.340366'
